export const GET_LANG_ID_START = "GET_LANG_ID_START";
export const GET_LANG_ID_SUCCESS = "GET_LANG_ID_SUCCESS";
export const GET_LANG_ID_FAILER = "GET_LANG_ID_FAILER";

export const GET_LANG_ALL_START = "GET_LANG_ALL_START";
export const GET_LANG_ALL_SUCCESS = "GET_LANG_ALL_SUCCESS";
export const GET_LANG_ALL_FAILER = "GET_LANG_ALL_FAILER";
export const GET_USER = "GET_USER";